- name: Playbook to set jmeter properties
  hosts: servers
  remote_user: ubuntu
  tasks:
    - name: Update ubuntu  
      apt:
        update_cache: yes

    - name: Copy bash file to set jmeter props
      copy:
        src: /home/pablo/DevOps/CopaCom/AnsibleMaster/edit-jmeter-props.sh
        dest: /home/ubuntu
        owner: ubuntu
        mode: '0744'
    
    - name: Execute script to set jmeter hosts
      shell:
        cmd: cd /home/ubuntu && bash edit-jmeter-props.sh