- name: Playbook to install ansible and send the slave folder
  hosts: servers
  remote_user: ubuntu
  tasks:
  - name: install ansible
    apt:
        update_cache: yes
        name: ansible
        state: latest

  - name: create git repo folder
    shell:
      cmd: mkdir -p /home/ubuntu/ansible

  - name: clone slave playbooks
    git:
       repo: https://github.com/fajardodiaz/ansible_slaves.git
       dest: /home/ubuntu/ansible
       clone: yes
       update: yes